name: 构建

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/构建.yml'

  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/构建.yml'

jobs:
  build:
    strategy:
      matrix:
        type: [grub2-fyde]

    name: 构建 ${{ matrix.type }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: 安装依赖软件包
      run: sudo apt-get install gettext

    - name: 构建 ${{ matrix.type }}
      run: sudo bash ./构建.sh

    - name: 上传到此处
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.type }}
        path: |
            grub2-fyde.zip
            grub2/grub2-fyde/grub2-fyde.xz

    - name: 发布
      uses: softprops/action-gh-release@v2
      with:
        name: "grub2-fyde-v20.0"
        tag_name: v20test1
        make_latest: true
        body_path: docs/发布模板.md
        files: |
          grub2-fyde.zip